// <auto-generated />
using System;
using FitnessApp.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.API.Migrations
{
    [DbContext(typeof(FitnessAppContext))]
    [Migration("20231230160548_AddWorkoutTypeDateAndLength")]
    partial class AddWorkoutTypeDateAndLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FitnessApp.API.Entities.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Intensity = "Easy",
                            Name = "Triceps pulldown",
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            Intensity = "Hard",
                            Name = "Shoulder press",
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 3,
                            Intensity = "Easy",
                            Name = "Bicep curl",
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 4,
                            Intensity = "Medium",
                            Name = "Chest fly",
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 5,
                            Intensity = "Easy",
                            Name = "Hamstring curl",
                            WorkoutId = 3
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 9, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 90,
                            Name = "Training 14/09",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 9, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 120,
                            Name = "Training 17/09",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 9, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 120,
                            Name = "Training 20/09",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 12, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 31,
                            Name = "Laufen 28/12",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 33,
                            Name = "Laufen 30/12",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Set", b =>
                {
                    b.HasOne("FitnessApp.API.Entities.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Workout", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
