// <auto-generated />
using System;
using FitnessApp.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.API.Migrations
{
    [DbContext(typeof(FitnessAppContext))]
    [Migration("20231102215400_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FitnessApp.API.Entities.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Intensity = "Easy",
                            Name = "Triceps pulldown",
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            Intensity = "Hard",
                            Name = "Shoulder press",
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 3,
                            Intensity = "Easy",
                            Name = "Bicep curl",
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 4,
                            Intensity = "Medium",
                            Name = "Chest fly",
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 5,
                            Intensity = "Easy",
                            Name = "Hamstring curl",
                            WorkoutId = 3
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Training 14/09"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Training 17/09"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Training 20/09"
                        });
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Set", b =>
                {
                    b.HasOne("FitnessApp.API.Entities.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("CityId");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Workout", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
